### PR TITLE
Resample tweaks

### PR DESCRIPTION
**Pull request by endolith**
Sorry for taking so long to look through this. I started making some changes to your changes, and there might be more

### CODE REVIEW

**Comment by larsoner** [comment]
Looks good so far

**Comment by endolith** [comment]
So some of these changes are obviously good (like removing extraneous things) , others I'm not sure about, (like reordering by stage instead of real-complex, or doing the FFT before rejecting an invalid window parameter) and I'm not 100% sure I didn't break something

**Comment by larsoner** [comment]
Do the tests pass locally for you? IIRC I had made them more complete so I'd trust them to check for breakages

**Comment by endolith** [comment]
Is there a way to test without building the entire project? :/

**Comment by larsoner** [comment]
Not that I know of. I'll pull and see if they pass

**Comment by endolith** [comment]
I converted them into plain commands and they don't seem to be passing, I'm trying to figure out what the problem is

**Comment by larsoner** [comment]
It breaks here

https://github.com/larsoner/scipy/pull/8/commits/51749f3d44648c1b6cada17ec7e40559c7ee5f91#diff-97a2088dd3cb8cda2ae551fa9357d5a8L2315

Putting the `num` back in makes it at least pass on that commit

**Comment by larsoner** [comment]
... then cherry-picking along, the next change that breaks it is 

https://github.com/larsoner/scipy/pull/8/commits/78a86f89a80a603fe97dc9c8005ee123467e2d7d

**Comment by larsoner** [comment]
Okay putting `num` back in after 51749f3 and omitting 78a86f8 things pass. Want to push a commit to make those two changes, then I can squash and merge?

**Comment by larsoner** [comment]
(or I can do some commit magic to take care of it)

**Comment by larsoner** [comment]
Squashed everything to this commit:

https://github.com/larsoner/scipy/commit/104c973a4ec47ba3a078cdc77bbbc8ee441c2e0f

If you're happy with it I can just cherry-pick it into my branch

**Comment by larsoner** [comment]
Done so closing, but if there is something wrong with omitting 104c973 and restoring the `num` that was removed in 51749f3 let me know

**Comment by endolith** [comment]
Yes that's fine

**Pull request closed without merging**
